---
title: "Rworksheets_MAMINTA#2"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1. 
x <- -5:5
x
```


```{r}
x <- 1:7
x
```

```{r}
#2.
seq(1, 3, by=0.2)
```

```{r}
#3. 
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
18)

print(ages[3])

print(ages[c(2, 4)])

print(ages[-1])

```


```{r}
#4.
x <- c("first"=3, "second"=0, "third"=9)
x
x[c("first", "third")]
#The Output shows that the value is 3 and 9.
```


```{r}
#5. Create a sequence x from -3:2.
x <- -3:2
x
x[2] <- 0
x
#The output shows that [2] was replaced by 0.
```

```{r}
#6. *The following data shows the diesel fuel purchased by Mr. Cruz.
Month <- c("Jan", "Feb", "March" ,"April" , "May", "June")
Priceperliter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
Liters <- c(25, 30, 40, 50, 10, 45)

fuel <- data.frame(Month, Priceperliter, Liters)
fuel

ave <- weighted.mean(Liters, Priceperliter)
ave
#The average fuel is [1] 32.65152
```

```{r}
#7.
rivers  
# a. Type “rivers” in your R console. Create a vector data with 7
#elements, containing the number of elements (length) in rivers,
#their sum (sum), mean (mean), median (median), variance (var)
#standard deviation (sd), minimum (min) and maximum (max).
data <- c(
  length(rivers), 
  sum(rivers),  
  mean(rivers),     
  median(rivers),   
  var(rivers),    
  sd(rivers),     
  min(rivers),    
  max(rivers)       
)
data
#b. What are the results?
#[1]    141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708    135.0000   3710.0000
```

```{r}
#8.
ranking <- 1:25

celebrity <- c(
  "Tom Cruise","Rolling Stones","Oprah Winfrey",
  "U2","Tiger Woods","Steven Spielberg",
  "Howard Stern","50 Cent","Cast of the Sopranos",
  "Dan Brown","Bruce Springsteen",
  "Donald Trump","Muhammad Ali","Paul McCartney",
  "George Lucas","Elton John",
  "David Letterman","Phil Mickelson","J.K. Rowling",
  "Brad Pitt","Peter Jackson",
  "Dr. Phil McGraw","Jay Lenon","Celine Dion","Kobe Bryant"
)

pay <- c(
  67,90,225,110,90,332,302,41,52,88,55,44,55,
  40,233,34,40,47,75,25,39,45,32,40,31
)

# Combine into a data frame for readability
forbes <- data.frame(Ranking=ranking, Celebrity=celebrity, Pay=pay)
forbes
#Modifying
forbes[forbes$Celebrity == "J.K. Rowling", ]
forbes[forbes$Celebrity == "J.K. Rowling", "Ranking"] <- 15
forbes[forbes$Celebrity == "J.K. Rowling", "Pay"] <- 90
forbes[forbes$Celebrity == "J.K. Rowling", ]

#INTERPRETATION

#The Forbes dataset shows the 25 most powerful celebrities ranked by their
#influence and annual earnings. After modification, J.K. Rowling’s ranking 
#changed from 19th to 15th, and her annual pay increased from 75 million to 90
#million USD. This adjustment places her closer to top-earning celebrities such 
#as George Lucas (233 million) and Oprah Winfrey (225 million), highlighting 
#her strong financial success and influence in comparison with other major 
#figures in entertainment, sports, and media.
```